### ISSUE TITLE
Trouble running the example file

### ISSUE THREAD

**Issue by GKBlueBoT-sys** [bobbypaton/wSterimol#5]
Hello. I was running the example pentane.pdb file, but upon entering the `wSterimol [[id 1, id 3, id 4, id 5],[id 3, id 4, id 5, id 2]], id 1, id 3` line, it shows the following error:
`Traceback (most recent call last):
  File "D:\pymol\wSterimol\mopac example\wSterimol.py", line 28, in wSterimol
    if optimisation(directory, walltime, verbose, setup_path):
  File "D:\pymol\wSterimol\mopac example\optimisation.py", line 72, in optimisation
    message = "   %-30s" % (filesplit[0]+".out") +"  %12.6f" % out.ENERGY
AttributeError: 'getoutData' object has no attribute 'ENERGY'`
Does this have something to do with the setup.ini file? Is the setup file read automatically? I tried setting OPTIMISATION to NO, but the error keeps repeating,

Thanks in advance!

**Comment by thtugwell** [comment]
Also having this issue. Was anyone ever able to resolve this?

**Comment by Shun-chem** [comment]
It seems this problem comes from the update made in MOPAC2016. This wSterimol program uses "TOTAL ENERGY" value in the output file from MOPAC (*.out), but the current version of MOPAC2016 does not report this value with the default setting. To make this value outputted from MOPAC, one can rewrite the line 80 in the prepare_file.py to
```python
lines.append("%s charge=%s %s\n" DISP% (setup.SE, setup.charge, setup.scf) )
``` 
so that proper input file for MOPAC is made by the wSterimol program.
